// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTokens() {
  return window['go']['main']['App']['ClearTokens']();
}

export function GetTokens() {
  return window['go']['main']['App']['GetTokens']();
}

export function StartTokenServer() {
  return window['go']['main']['App']['StartTokenServer']();
}
